---
kind: pipeline
type: docker
name: arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: ubuntu-xenial
    image: ubuntu:xenial
    commands:
      - uname -m
      - apt-get -yq update
      - apt-get install libevent-dev
      - apt-get install libssl-dev
      - apt-get -yq install gcc make file
      - make
# https://docker-runner.docs.drone.io/configuration/trigger/
trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: arm32
platform:
  os: linux
  arch: arm
steps:
  - name: ubuntu-xenial
    image: ubuntu:xenial
    commands:
      - uname -m
      - apt-get -yq update
      - apt-get install libevent-dev
      - apt-get install libssl-dev
      - apt-get -yq install gcc make file
      - make
trigger:
  branch:
    - master