---
kind: pipeline
type: docker
name: arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: ubuntu-trusty
    image: ubuntu:trusty
    commands:
      - uname -m
      - apt-get -yq update
      - apt-get -yq  install libevent-dev
      - apt-get -yq install libssl-dev
      - apt-get -yq install gcc make file
      - make ENABLE_STATIC=true DISABLE_SHADOWSOCKS=true
# https://docker-runner.docs.drone.io/configuration/trigger/
trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: arm32
platform:
  os: linux
  arch: arm
steps:
  - name: ubuntu-trusty
    image: ubuntu:trusty
    commands:
      - uname -m
      - apt-get -yq update
      - apt-get -yq install libevent-dev
      - apt-get -yq install libssl-dev
      - apt-get -yq install gcc make file
      - make ENABLE_STATIC=true DISABLE_SHADOWSOCKS=true
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: gh_token
      files:
        - ./redsocks2
    when:
      event: tag
    
trigger:
  branch:
    - master
    
