language: c

compiler:
  - gcc
#  - clang
arch:
  - amd64
  - arm64
os: linux  # different CPU architectures are only supported on Linux

install:
 - sudo apt-get update
 - sudo apt-get install libssl-dev
 - sudo apt-get install libevent-dev

script:
  - git submodule update --init --recursive
  - make