language: c

compiler:
  - gcc
arch:
  - arm64
os: linux  # different CPU architectures are only supported on Linux

env:
# https://packages.ubuntu.com/xenial/crossbuild-essential-armhf
  - CC=arm-linux-gnueabihf-gcc
  - SETARCH="setarch linux32 --verbose --32bit"
before_install:
  - sudo dpkg --add-architecture armhf
  - sudo apt-get update -yq
# There is no gcc-multilib on arm64.
# https://packages.ubuntu.com/xenial/gcc-multilib
# To run bin/hello, we need libc6:armhf deb package.
# Check `ldd bin/hello`.
# https://askubuntu.com/questions/133389
  - |-
    sudo apt-get -yq install \
      crossbuild-essential-armhf \
      libc6:armhf
    
install:
 - sudo apt-get update
 - sudo apt-get install libssl-dev
 - sudo apt-get install libevent-dev

script:
  - git submodule update --init --recursive
  - make