name: linux_build

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install depends
      run: |
        sudo apt update
        sudo apt install -y libssl1.0-dev libevent-dev
    - name: mkdir
      run: mkdir build
    - name: buid
      run: make --build build/ --target all
    - name: Upload Example binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary
        path: build/src/Example